# Generated by Django 3.1.7 on 2021-04-06 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
